spring:
  application:
    name: service-discovery
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      name: service-discovery
      profile: dev
      fail-fast: true
